import type { Product, Category } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: "1", name: "New & Featured", slug: "new", parent_id: null, description: null, image_url: null, sort_order: 1, created_at: "" },
  { id: "2", name: "Play", slug: "play", parent_id: null, description: null, image_url: null, sort_order: 2, created_at: "" },
  { id: "3", name: "Home", slug: "home", parent_id: null, description: null, image_url: null, sort_order: 3, created_at: "" },
  { id: "4", name: "Kitchen", slug: "kitchen", parent_id: null, description: null, image_url: null, sort_order: 4, created_at: "" },
  { id: "5", name: "Wellness", slug: "wellness", parent_id: null, description: null, image_url: null, sort_order: 5, created_at: "" },
];

const placeholder = (seed: number) =>
  `https://picsum.photos/seed/${seed}/600/600`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Robin 3D Puzzle",
    slug: "robin-3d-puzzle",
    description: "A beautiful 3D puzzle featuring a cheerful robin. Great for all ages.",
    price: 1800,
    compare_at_price: null,
    category_id: "2",
    category: MOCK_CATEGORIES[1],
    tags: ["new", "play", "puzzle"],
    is_active: true,
    is_featured: true,
    stock_quantity: 42,
    images: [{ id: "i1", product_id: "1", url: placeholder(10), alt: "Robin 3D Puzzle", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "2",
    title: "Bike Bell — Juicy Jingles",
    slug: "bike-bell-juicy-jingles",
    description: "Fruit-shaped bike bells that ring loud and look delightful.",
    price: 1200,
    compare_at_price: 1500,
    category_id: "1",
    category: MOCK_CATEGORIES[0],
    tags: ["new", "on-the-go"],
    is_active: true,
    is_featured: true,
    stock_quantity: 18,
    images: [{ id: "i2", product_id: "2", url: placeholder(20), alt: "Juicy Jingles Bike Bell", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "3",
    title: "Axolotl Punch Needle Kit",
    slug: "axolotl-punch-needle-kit",
    description: "Create your own adorable axolotl with this punch needle embroidery kit.",
    price: 2400,
    compare_at_price: null,
    category_id: "2",
    category: MOCK_CATEGORIES[1],
    tags: ["new", "craft"],
    is_active: true,
    is_featured: true,
    stock_quantity: 30,
    images: [{ id: "i3", product_id: "3", url: placeholder(30), alt: "Axolotl Punch Needle Kit", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "4",
    title: "Golf Wine Aerator",
    slug: "golf-wine-aerator",
    description: "Aerate your wine in style with this golf ball-shaped wine aerator.",
    price: 1600,
    compare_at_price: null,
    category_id: "4",
    category: MOCK_CATEGORIES[3],
    tags: ["kitchen", "bar", "gifts"],
    is_active: true,
    is_featured: true,
    stock_quantity: 55,
    images: [{ id: "i4", product_id: "4", url: placeholder(40), alt: "Golf Wine Aerator", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "5",
    title: "Light Up Pencil Set",
    slug: "light-up-pencil-set",
    description: "Pencils that light up at the tip — perfect for kids and the young at heart.",
    price: 900,
    compare_at_price: null,
    category_id: "2",
    category: MOCK_CATEGORIES[1],
    tags: ["new", "stationery", "kids"],
    is_active: true,
    is_featured: false,
    stock_quantity: 0,
    images: [{ id: "i5", product_id: "5", url: placeholder(50), alt: "Light Up Pencil Set", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "6",
    title: "Woodpecker Garden Shears",
    slug: "woodpecker-garden-shears",
    description: "Precision pruning shears shaped like a cheerful woodpecker.",
    price: 2200,
    compare_at_price: 2800,
    category_id: "3",
    category: MOCK_CATEGORIES[2],
    tags: ["garden", "tools", "home"],
    is_active: true,
    is_featured: true,
    stock_quantity: 12,
    images: [{ id: "i6", product_id: "6", url: placeholder(60), alt: "Woodpecker Garden Shears", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "7",
    title: "Magnetic Hourglass",
    slug: "magnetic-hourglass",
    description: "Watch magnetic sand flow in beautiful patterns inside this elegant hourglass.",
    price: 3200,
    compare_at_price: null,
    category_id: "3",
    category: MOCK_CATEGORIES[2],
    tags: ["home", "decor", "desk"],
    is_active: true,
    is_featured: true,
    stock_quantity: 8,
    images: [{ id: "i7", product_id: "7", url: placeholder(70), alt: "Magnetic Hourglass", sort_order: 0 }],
    created_at: "",
  },
  {
    id: "8",
    title: "Bear Hug Mug",
    slug: "bear-hug-mug",
    description: "A cozy ceramic mug with bear paw handles. Perfect for morning coffee.",
    price: 1400,
    compare_at_price: null,
    category_id: "4",
    category: MOCK_CATEGORIES[3],
    tags: ["kitchen", "gifts", "new"],
    is_active: true,
    is_featured: false,
    stock_quantity: 24,
    images: [{ id: "i8", product_id: "8", url: placeholder(80), alt: "Bear Hug Mug", sort_order: 0 }],
    created_at: "",
  },
];

export const MOCK_BEST_SELLERS = MOCK_PRODUCTS.filter((p) =>
  ["golf-wine-aerator", "magnetic-hourglass", "robin-3d-puzzle", "bear-hug-mug"].includes(p.slug)
);
